#
# AzLink Bukkit config
#

# When enabled, vanished players will be ignored by AzLink: they won't be
# included in players count and won't receive commands while vanished.
# Try disabling this option if you have some issues.
ignore-vanished-players: false

# When enabled, new users registered with the AuthMe plugin will automatically be registered on the website
# WARNING: You need AuthMeReloaded version 5.6.0-beta2 or newer AND Azuriom version 1.0.0 or newer!
# If you are using multiples serves, you should use the same database for AuthMe to prevent users
# from registering multiple times
authme-integration: false
